name: Deploy Frontend to S3

on:
    push:
        paths:
            - "fashion-frontend/**"
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: fashion-frontend

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker Image
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fashion-frontend:latest .

            - name: Push Docker Image
              run: docker push ${{ secrets.DOCKER_USERNAME }}/fashion-frontend:latest

            - name: Install dependencies
              run: npm install

            - name: Build React App
              run: npm run build

            - name: Deploy to S3
              uses: jakejarvis/s3-sync-action@master
              with:
                args: --delete
              env:
                AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
                SOURCE_DIR: fashion-frontend/build

            - name: Invalidate CloudFront Cache
              uses: chetan/invalidate-cloudfront-action@v2
              env:
                AWS_REGION: ${{ secrets.AWS_REGION }}
                DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
                PATHS: "/*"
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}